services:
  - type: web
    name: convivir-v4
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn start:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TF_ENABLE_ONEDNN_OPTS
        value: 0
      - key: FLASK_ENV
        value: production

